### PR TITLE
last PR for screenshotter

### PR DESCRIPTION
**Pull request by ConnorDoesDev**
embarrassing typo. I blame the IDE.....

### CODE REVIEW

**Comment by MrPandir** [comment]
It seems you accidentally committed the update `pnpm-lock.yaml` 👀

**Comment by ConnorDoesDev** [comment]
> It seems you accidentally committed the update `pnpm-lock.yaml` 👀

I'm on mobile rn, any way to remove it via Git Mobile?

**Comment by ConnorDoesDev** [comment]
ok i broke the whole thing by completely removing it 
i hate git mobile

**Comment by ConnorDoesDev** [comment]
plugin still broken on prod o7

**Pull request merged**
